imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    locale_names:
        en: English
        de: Deutsch
        fr: Français
        es: Español
        it: Italiano
        pl: Polskie
        kr: 한국어
        jp: 日本語
        zh: 中文
    supported_locales:
        - en
        - es
    default_locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["en"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"
        cookie_lifetime: 604800
    fragments:       ~
    http_method_override: true

# Twig
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        default_locale: %default_locale%
        supported_locales: %supported_locales%
        cards_data: "@cards_data"
        deck_validation_helper: "@deck_validation_helper"
        google_analytics_tracking_code: "%google_analytics_tracking_code%"
        google_adsense_client: "%google_adsense_client%"
        google_adsense_slot: "%google_adsense_slot%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Assetic
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AppBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        jsqueeze: ~

# Doctrine
doctrine:
    dbal:
        driver:   pdo_mysql
        server_version: 5.6
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore
                dql:
                    string_functions:
                        replace: AppBundle\DQL\ReplaceFunction
                        binary: AppBundle\DQL\BinaryFunction
                    numeric_functions:
                        power: AppBundle\DQL\PowerFunction
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false

# JMSI18nRoutingBundle
jms_i18n_routing:
    default_locale: %default_locale%
    locales: %supported_locales%
    strategy: custom
    hosts:
        en: "%website_url%"
        es: "es.%website_url%" 
    redirect_to_host: true

# Swiftmailer
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    registration:
        confirmation:
            enabled: true

# FOSJsRoutingBundle
fos_js_routing:
    routes_to_expose: [ '.*' ]


# NelmioApiDocBundle
nelmio_api_doc: ~

# FOSOAuthServerBundle
fos_oauth_server:
    db_driver: orm       # Driver availables: orm, mongodb, or propel
    client_class:        AppBundle\Entity\Client
    access_token_class:  AppBundle\Entity\AccessToken
    refresh_token_class: AppBundle\Entity\RefreshToken
    auth_code_class:     AppBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager

services:
    fos_user.doctrine_registry:
        alias: doctrine

# JsTranslationBundle
bazinga_js_translation:
    locale_fallback: %default_locale%
    active_locales:
        - en
        - es
