blog:
  path: /
  defaults:
    _controller: AppBundle:Blog:index

blog_new:
  path: /new
  defaults:
    _controller: AppBundle:Blog:new

blog_show:
  path: /{id}/show
  defaults:
    _controller: AppBundle:Blog:show

blog_index:
  path: /
  defaults:
    _controller: AppBundle:Blog:index

blog_create:
  path: /create
  defaults:
    _controller: AppBundle:Blog:create
  methods: [ post ]

blog_edit:
  path: /{id}/edit
  defaults:
    _controller: AppBundle:Blog:edit

blog_update:
  path: /{id}/update
  defaults:
    _controller: AppBundle:Blog:update
  methods: [ post, put ]

blog_delete:
  path: /{id}/delete
  defaults:
    _controller: AppBundle:Blog:delete
  methods: [ post, delete ]

