
cards_list:
    path: /set/{pack_code}/{view}/{sort}/{page}
    defaults:
        _controller: AppBundle:Search:list
        view: list
        sort: set
        page: 1

cards_zoom:
    path: /card/{card_code}
    defaults:
        _controller: AppBundle:Search:zoom

cards_cycle:
    path: /cycle/{cycle_code}/{view}/{sort}/{page}
    defaults:
        _controller: AppBundle:Search:cycle
        view: list
        sort: faction
        page: 1

cards_search:
    path: /search
    defaults:
        _controller: AppBundle:Search:form

cards_find:
    path: /find
    defaults:
        _controller: AppBundle:Search:find

cards_processSearchForm:
    path: /process
    defaults:
        _controller: AppBundle:Search:process
