
card_review_post:
    path: /post
    methods: [POST]
    defaults: 
        _controller: AppBundle:Review:post

card_review_edit:
    path: /edit
    methods: [POST]
    defaults: 
        _controller: AppBundle:Review:edit

card_review_like:
    path: /like
    methods: [POST]
    defaults:
        _controller: AppBundle:Review:like

card_review_remove:
    path: /remove/{id}
    defaults:
        _controller: AppBundle:Review:remove
        
card_reviewcomment_post:
    path: /comment
    methods: [POST]
    defaults: 
        _controller: AppBundle:Review:comment
        