
tag_add:
    path: /add
    methods: [POST]
    defaults:
        _controller: AppBundle:Tag:add

tag_remove:
    path: /remove
    methods: [POST]
    defaults:
        _controller: AppBundle:Tag:remove

tag_clear:
    path: /clear
    methods: [POST]
    defaults:
        _controller: AppBundle:Tag:clear
