admin_faction:
    path:  /
    defaults: { _controller: "AppBundle:Faction:index" }

admin_faction_show:
    path:  /{id}/show
    defaults: { _controller: "AppBundle:Faction:show" }

admin_faction_new:
    path:  /new
    defaults: { _controller: "AppBundle:Faction:new" }

admin_faction_create:
    path:  /create
    defaults: { _controller: "AppBundle:Faction:create" }
    methods: [ post ]

admin_faction_edit:
    path:  /{id}/edit
    defaults: { _controller: "AppBundle:Faction:edit" }

admin_faction_update:
    path:  /{id}/update
    defaults: { _controller: "AppBundle:Faction:update" }
    methods: [ post, put ]

admin_faction_delete:
    path:  /{id}/delete
    defaults: { _controller: "AppBundle:Faction:delete" }
    methods: [ post, delete ]
