admin_cycle:
    path:  /
    defaults: { _controller: "AppBundle:Cycle:index" }

admin_cycle_show:
    path:  /{id}/show
    defaults: { _controller: "AppBundle:Cycle:show" }

admin_cycle_new:
    path:  /new
    defaults: { _controller: "AppBundle:Cycle:new" }

admin_cycle_create:
    path:  /create
    defaults: { _controller: "AppBundle:Cycle:create" }
    methods: [ post ]

admin_cycle_edit:
    path:  /{id}/edit
    defaults: { _controller: "AppBundle:Cycle:edit" }

admin_cycle_update:
    path:  /{id}/update
    defaults: { _controller: "AppBundle:Cycle:update" }
    methods: [ post, put ]

admin_cycle_delete:
    path:  /{id}/delete
    defaults: { _controller: "AppBundle:Cycle:delete" }
    methods: [ post, delete ]
