AppBundle\Entity\Blog:
    type: entity
    table: blog
    fields:
      id:
        type: integer
        id: true
        generator:
          strategy: AUTO
      description:
        type: string
        length: 1024
        nullable: false
      date:
        type: datetime
        nullable: false
        column: date
        gedmo:
          timestampable:
            on: create