AppBundle\Entity\Errata:
  type: entity
  table: errata
  manyToOne:
    card:
      targetEntity: Card
      inversedBy: erratas
      joinColumn:
        name: card_id
        referencedColumnName: id
    user:
      targetEntity: User
      inversedBy: erratas
      joinColumn:
        name: user_id
        referencedColumnName: id
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    dateCreation:
      type: datetime
      nullable: false
      column: date_creation
      gedmo:
        timestampable:
          on: create
    dateUpdate:
      type: datetime
      nullable: false
      column: date_update
      gedmo:
        timestampable:
          on: update
    textMd:
      type: text
      nullable: false
      column: text_md
    textHtml:
      type: text
      nullable: false
      column: text_html

